---
- name: Install rustup system requirements via apt.
  become: True
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ rustup_dependencies }}"

- name: Install crate system dependencies via apt.
  become: True
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ crate_dependencies }}"

- name: Install rustup, cargo and creates.
  import_tasks: install-rust.yml
  become: True
