---
- name: Add fish repository from PPA and install its signing key on Ubuntu target.
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3

- name: Install the fish package.
  become: true
  ansible.builtin.apt:
    name: fish
    state: present
    update_cache: yes

- name: Ensure fish is added to /etc/shells.
  become: true
  ansible.builtin.lineinfile:
    state: present
    path: /etc/shells
    regexp: '^/bin/fish'
    line: /bin/fish
    owner: root
    group: root
    mode: u=rx,g=rx,o=r
