---
# cheat - CLI cheatsheets - https://github.com/cheat/cheat
- name: Check latest cheat binary release.
  uri:
    url: "https://api.github.com/repos/cheat/cheat/releases/latest"
    return_content: true
  register: cheat_latest

- name: "Installing cheat {{ cheat_latest.json.tag_name }}."
  loop: "{{ cheat_latest.json.assets }}"
  when: "'cheat-linux-amd64.gz' in item.name"
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    keep_newer: yes
