---
- name: Link the message of the day.
  become: True
  ansible.builtin.shell: ln -sfv "{{ user.home }}/.dotfiles/common/motd/motd" /etc/


- name: We don't need the MOTD help text.
  become: True
  ansible.builtin.file:
    path: /etc/update-motd.d/10-help-text
    state: absent


- name: And we deactivate the dynamic news.
  become: True
  ansible.builtin.lineinfile:
    path: /etc/default/motd-news
    regexp: '^ENABLED'
    line: ENABLED=0
    state: present
    create: yes
    owner: root
    group: root
    mode: '0644'
